### ISSUE TITLE
bug: Filenames that conflict variables within Gruntfile.js will cause errors.

### ISSUE THREAD

**Issue by davechiu** [assemble/assemble#417]
With a pretty vanilla installation of assemble, if you name a partial the name of a variable or object being used by a task coming after the assemble task the server will error out.

Example project: https://github.com/davechiu/assemble-io-naming-bug-test

In this example, there is a partial called `connect.hbs` which will interfere with the connect object in `Gruntfile.js`. Running assemble as part of a larger task such as `grunt serve` will error with: `Verifying property connect.livereload exists in config...ERROR` when the task hits `connect:livereload` or potentially any task accessing variables in `Gruntfile.js` after the `assemble` task. Simply running `grunt assemble` will be fine. You can successfully work your way to running the `grunt serve` task by running `grunt assemble` manually first, and then commenting out the `clean:server` and `assemble` tasks to serve the manually assembled code in temp.

You won't notice the issue straight away if a task such as `grunt serve` is already running, but the next time you go to start the server or build you will be baffled as to why something that was just working suddenly errors. Rename the file and the project will run again.

Because assemble is able to run successfully, it might be nice for a warning to be thrown for a potential conflict later on.

**Comment by jonschlinkert** [comment]
Closing this issue since Assemble has been completely refactored from the ground up and released as v0.6.0. 

However, if this is related to grunt-assemble, and the issue or feature request is still valid, please [use this link](https://github.com/assemble/grunt-assemble/issues/new?body=Moved%20from%20assemble%2Fassemble%23417) to create a new issue on the grunt-assemble repository.

If you do create a new issue, please be sure to include:

* The version of `assemble` you are using.
* Your `assemblefile.js` (This can be in a gist)
* The commandline output. (Screenshot or gist is fine)
* The expected result versus what's actually happening
