### ISSUE TITLE
Re-generate only changed pages?

### ISSUE THREAD

**Issue by phobia** [assemble/assemble#451]
Hi,

I'm triggering Assemble using a Grunt Watch task. This rebuilds all pages.

Is it possible to configure Assemble so that only the changed page is rebuilt?

I tried the "grunt newer" task, which seems to detect correctly what has changed, but assemble still regenerates all pages.

**Comment by cschweda** [comment]
I'm interested in this as well. Will the next version of Assemble speed up the build process with the caching mentioned above?

I'm about to start a project with Assemble that has -- essentially -- 600 or so pages. My concern is that each new page added requires the entire site to be re-assembled. Obviously, this is do-able but it does seem like it might be an issue as the site grows (potentially to 1000+ pages over the next year).

Not a bug, I realize -- and not something critical since most Assemble sites (I'm guessing) are relatively compact -- but I'm wondering if this is being considered for a future version.

**Comment by Zackio** [comment]
My way around this for my project is to do it in parts so grunt watches only a section of pages and triggers to render those pages so its not rending all the pages in the project when it doesn't need which takes a while.

**Comment by dustintheweb** [comment]
This would be an amazing feature to have. Is it safe to get my hopes up?

**Comment by doowb** [comment]
assemble 0.6.0 will have an update in a few days that will allow passing in a `since` option to `assemble.src`, so you can use `assemble.watch` and only read in files that have changed. I'll post an example when that's ready.

**Comment by dustintheweb** [comment]
@doowb my wildest dreams are coming true. TY & Godspeed!

**Comment by jonschlinkert** [comment]
If you're familiar with watching in general, you'll probably know this, but keep in mind that any and all files that share any kind of dependency tree will need to be watched for this to do what you expect. e.g. if you're templates are using json files, you'll to watch the templates and json files.

**Comment by Sebastian-Fitzner** [comment]
@doowb :thumbsup:

**Comment by Coder2012** [comment]
@doowb 

Do you have an update on your progress with this? I am also building many pages and components, it is taking about 30secs on a high spec machine.

**Comment by doowb** [comment]
@Coder2012 the more recent `assemble@beta` has the `since` feature so you can pass that in the options on `assemble.src` to only build files that have changed since the `since` time. You'll have to figure out that since time on your own right now since we aren't storing any of that information. Let me know if you run into any issues using it.

**Comment by pixelstew** [comment]
Hi there, is this feature documented anywhere? Got some looong compile times I'm battling with and this feature may resolve the issue.

**Comment by jonschlinkert** [comment]
> Hi there, is this feature documented anywhere? Got some looong compile times I'm battling with and this feature may resolve the issue.

I've never had even a "loong" compile time, much less one with **three** "o"s! That's insane! lol jk

maybe we can help if you can share some info about your setup:

- what version of assemble are you using? 
- what are you using for watching?
- what do your glob patterns look like? are you using double globstars? `**/*.hbs`. If so, how many total files are being globbed? 
- how many files are being rendered versus the number being watched? 
- how big is the avg. file? 
- is there front matter? if so, is it being parsed by a custom middleware? 
- are you using helpers? custom ones? 
- are you using custom middleware?
- custom `mergeContext` function?

**Comment by pixelstew** [comment]
Hi there,

Before I start I think i'm probably to blame here ;) I suspect my problem is based around the sheer number of partials I have created. 
I am building up modules using atomic design principles so I have a fair number of partials for basic html elements which then get nested inside more complex modules so on up to full page views.

It would be good to have a way to parse which templates are using the partial I have just edited and just update those.

I am going to refactor my gruntfile to see if I can set up my watch process more prudently too. 

I'll try and answer your list of questions

** Last render was 437 seconds

* v0.4.41
* grunt-contrib-watch
* I am using **/*.hbs globs 
* Rendering 37 pages made up of lots of partials ^^ see above
* file sizes are small but there are lots of em
* Front matter yes - no middleware parsing
* Only using helpers from handlebars helpers package
* nope
* nope

**Comment by jonschlinkert** [comment]
> I suspect my problem is based around the sheer number of partials I have created.

you are not alone my friend, I too suffer from partial mania. but they're so fun to create! 

okay, that aside, 437 secs seems really, really long. even if you have tons of partials. are there task dependencies that might be causing this? like minifiers or css pre-processors?

**Comment by pixelstew** [comment]
My Sass globbing/compiling takes a few seconds - last reported was 3.4 sec.

My watch > assemble process is definitely the bottleneck, each page takes like 15 seconds to render. I have 2 assemble processes - one which renders html of all the partials into a docs folder (happens in a flash as you'd expect). The other (loooong) one compiles pages using a layout file and front matter. The site is a style guide for a larger site i'm building so each module has it's own 'example' page. Each example page is a header > nav > rendered module (made up of nested partials) > code view block (which switches between the contents of the module's .hbs file or the resultant html that is generated) > footer.

I have pulled out the {{ embed }} helpers and the dynamic nav thinking they might be the bottleneck but...no dice.

I'm a bit puzzled - just trying to eliminate things at the moment - I'm going to watch a single file with grunt - make some edits to the process, and see if i can work out where the problem is. I'll let you know how I get on with that.

**Comment by jonschlinkert** [comment]
ok, there is definitely something wrong. a page should take about a millisecond to re-render in memory. actually I'm not sure it's this fast with grunt, but it is with the latest assemble. yesterday I was seeing about 10 pages re-render in 2-3 ms. something else is definitely wrong here.

**Comment by jonschlinkert** [comment]
any collections? it sounds like an infinitely loop is happening, or some error that isn't bubbling up

**Comment by doowb** [comment]
We saw this before with a large amount of templates/partials because in `grunt-assemble` we're merging all the data together and doing `grunt.process` on the entire config/context for every page. Might want to try the latest `grunt-assemble` and open the issue there. Or you might be able to switch to `assemble@0.6x`. I saw someone else do this with the atomic pattern and it cut their build down to 30-45 seconds from 10 minutes.

**Comment by pixelstew** [comment]
Right thanks for all your help guys but I have, contrary to my previous post, narrowed it down to the {{ embed }} helpers on the page. I think i'll set them up in some kind of final build process as they are only needed for production version of style-guide. 

Are these notoriously slow? 

edit - Looking at it now i can see where the bottleneck is - I have no way of knowing where each .hbs file for each template is located at layout level so the front matter variable looks like **/partial.hbs - it is obviously traversing the entire src folder to find the relevant file. My bad.

@doowb I'll keep an eye on that as this baby grows. Some way to go yet!

**Comment by jonschlinkert** [comment]
yeah but I think we only saw that happen on two or three projects. I forgot about that since it's been a year or two.

Given the sheer number of projects we've worked on with assemble (grunt-assemble), and we've built huge projects that were much faster than is being described. I don't think it's exclusively because we were merging the context in that version of assemble. If the context is small, that wouldn't cause this kind of problem. I'm guessing it's a cyclical reference or it's just a huge context being merged. not because 

It could also be a helper that's merging data onto the context somewhere... 

anyway, It goes without saying that if you have a ton of data and partials that get passed to the engine AND you necessarily have to merge multiple data sources to pass to templates as context at render time, unless you're using big blue to render your templates it's going to get exponentially slower as the project size increases. caching strategy also plays a role.

**Comment by jonschlinkert** [comment]
awesome, glad you found the issue! helpers and glob patterns were my first two thoughts... thanks for letting us know how you solved it!

**Comment by jonschlinkert** [comment]
btw, perhaps you can use a template in the front matter with a variable for the cwd, like:

```handlebars
---
foo: <%= somedir %>/**/partial.hbs
---
```

then create a variable in your grunt config or wherever it makes sense :

```js
assemble: {
  options: {
    somedir: 'foo/bar
  }
}
```

**Comment by pixelstew** [comment]
Yeah i am just tinkering with something along those lines now. Thanks for the advice.
