### ISSUE TITLE
Marked option: highlight callback function is undefined

### ISSUE THREAD

**Issue by duvillierA** [assemble/assemble#511]
The **callback** function to call when using an async highlighter is always undefined.

See the code below.

```js
  options: {
    flatten: true,
    partials: ['<%= path.doc %>/partials/**/*.hbs'],
    layout: ['<%= path.doc %>/layouts/default.hbs'],
    data: ['<%= path.doc %>/data/*.{json,yml}'],
    marked: {
      highlight: function (code, lang, callback) {
        console.log('lang', lang, callback);
        pygmentize({ lang: lang, format: 'html' }, code, function (err, result) {
          callback(null, result.toString());
        });
      }
    }
  },
```

**Comment by alejandroiglesias** [comment]
Hey @koopero, I was trying to implement your solution, but I couldn't because the Grunt task fails with the following output:

```
Running "assemble:pages" (assemble) task
Assembling dist/alerts.html ERROR
Warning: Cannot find module 'spawn-sync'
Please report this to https://github.com/chjj/marked. Use --force to continue.

Aborted due to warnings.
```

Am I missing something?
Thanks.

**Comment by alejandroiglesias** [comment]
Also, tried doing `npm install --save-dev spawn-sync`, but then Grunt task fails with another error:

```
Running "assemble:pages" (assemble) task
Assembling dist/alerts.html ERROR
Warning: ENOENT, no such file or directory '/var/folders/s5/bdvgymxs1hjgp6d7zrgyzn900000gn/T/spawn-sync_output_41525167a0ac3b364fe9a57ab'
Please report this to https://github.com/chjj/marked. Use --force to continue.

Aborted due to warnings.
```

**Comment by koopero** [comment]
Hey @alejandroiglesias. I don't know how much help I can be with this; I ended using [highlight.js](https://highlightjs.org/) rather than `pygmentize`, although I don't remember why exactly.

It sounds like the `pygmentize` process is failing. First, check that `pygmentize` is running properly from your command line. Next, take this little function apart and use `console.warn` to get a look at what marked is passing to the function, and if possible the `stderr` from spawn-sync. It could be that `lang` is missing or something.

Also, it's a bit of smell that you even need the `spawn-sync` module... [child_process.spawnSync](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) has been stable in node for a while now. You might consider upgrading.

Hope this helps.

**Comment by jonschlinkert** [comment]
closing since this refers to an outdated version of grunt-assemble
