### ISSUE TITLE
v.0.6.0 Can't get swig to work

### ISSUE THREAD

**Issue by andrefgneves** [assemble/assemble#636]
Hi, I'm trying to get assemble to render my Swig templates but having no luck. I believe I'm not setting it up to use Swig correctly.

Here's my setup:

##### Gulp task (coffee)
```coffee```
gulp         = require 'gulp'
debug        = require 'gulp-debug'
config       = require '../config'
engines      = require 'engines'
extname      = require 'gulp-extname'
assemble     = require 'assemble'
browserSync  = require 'browser-sync'
gulpAssemble = require 'gulp-assemble'

options =
    data:       config.src + '/data/*.{json,yml}'
    layouts:    config.src + '/templates/layouts/*.swig'
    partials:   config.src + '/templates/partials/*.swig'
    production: false

build = ->
    assemble.engine 'swig', engines.swig

    gulp.src config.src + '/templates/pages/*.swig'
        .pipe debug()
        .pipe gulpAssemble assemble, options
        .pipe extname()
        .pipe gulp.dest config.dest
        .pipe browserSync.reload stream: true

gulp.task 'assemble', build

gulp.task 'assemble:dist', ->
    options.production = true

    build()
```

##### Layout

```HTML```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>{{title}} - My site</title>
    </head>
    <body>
        <main>
            {{> body}}
        </main>
    </body>
</html>
```

##### Template

```HTML```
---
title: Home
---

<article>
    <h1>hello world!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
</article>
```

I just get the templates back without them being wrapped in the layout. And if I use any swig in the template, I get errors coming from the engine-handlebars module, so I'm definitely setting up things wrong.

Can you please take a look and let me know what I'm doing wrong? Thanks in advance.

**Comment by doowb** [comment]
A couple of things are happening:

 - The options like `data`, `partials`, and `layouts` need to be set on the `assemble` object directly. [docs](https://github.com/assemble/assemble/tree/v0.6.0#templates)
 - The layout needs to use `{% body %}` as the tag instead of `{{> body }}`. [docs](https://github.com/assemble/assemble/tree/v0.6.0#layout)
 - The layout needs to be set no the `assemble.options` if not specified in the page front-matter. `assemble.option('layout', 'layout');`

After making those changes, if you're still having an issue, try the same setup with assemble directly (instead of gulp).

**Comment by doowb** [comment]
@andrefgneves I found some additional issues I'll be talking with @jonschlinkert about later today. I'll update this issue when they're solved.

**Comment by jonschlinkert** [comment]
closing so this can be moved to gulp-assemble. please only create issues directly related to assemble here (e.g. without gulp)
