### ISSUE TITLE
How do you run assemble 0.6.0 from gulp to create HTML from JSON?

### ISSUE THREAD

**Issue by agross** [assemble/assemble#639]
I'm trying to run assemble from gulp.

There is assemble, template and gulp-assemble.
* How do I run assemble from gulp?
* Where should I define my tasks?
* Do I even need to define tasks? 
* Should I define assemble tasks in gulpfile.js?

Here is what I'm trying to do:
```js
gulp.task('generate-html', function() {
  // Load all product metadata.
  return assemble.src('source/data/**/*.json')
    // Generate HTML from JSON metadata.
    .pipe(gulpAssemble(assemble, { layout: 'default' }))
    // Save as HTML.
    .pipe(assemble.dest('dist'));
});
```

I think my environment might also be a bit unusual for assemble. My input data (JSON) only consists of metadata, i.e. the "input" template does not have content (I'm OK with dummy content, but I won't use it). Reading the docs I think I need to create a custom loader, here is what I got so far:

```js
assemble.create('product', { isRenderable: true },
  function(pattern) {
    console.log(pattern);

    var files = glob.sync(pattern);
    if (files.length === 0) {
      return null;
    }

    var templates =  _.map(files, function(file){
      var content = fs.readFileSync(file, 'utf8');
      var name = path.basename(file, path.extname(file));

      var template = {
        name: {
          path: file,
          data: JSON.parse(content),
          content: 'dummy content to have the template pass validation'  
        }
      };

      return template;
    });

    // How to return > 1 template for pattern?
    return templates[0];
  }
);
```

When I use this with `assemble.product('source/data/42.json');` I get that one file passed as `pattern`. As soon as I switch to plural/globs I get the glob passed, and then I also need to handle the globbing. Why is that? I found [this](https://github.com/jonschlinkert/template/blob/master/docs/recipes/api-create.md#create), [this](https://github.com/jonschlinkert/template/blob/master/docs/recipes/get-the-most-out-of-template.md#load) and especially [this](https://github.com/jonschlinkert/template/blob/master/docs/recipes/loaders.md) documentation showing another parameter set, but it doesn't work. Is it outdated? Especially the `next` args are objects rather than functions.

So far, assemble and the accompanying libraries proved to be very frustrating to me :( But perhaps it's just me as I started this whole node/gulp thing just this week. Any help clearing up my questions would be highly appreciated!

**Comment by doowb** [comment]
You've got a great start for just starting this week!

[This PR](https://github.com/assemble/assemble/pull/559) tries to explain the assemble 0.6.0 API and how it's split up.

`template` handles keeping a reference to templates that are loaded, engines to render the templates, helpers to be used in templates, data/context to use when rendering templates, and middleware to do some extra processing to templates outside of the actual rendering.

`assemble` adds the Tasks API which handles creating tasks (`assemble.task`), reading pages from the file system (`assemble.src`), and writing pages to the file system (`assemble.task`). Additionally, when reading pages, assemble loads those into `template` using the default loader, then renders pages flowing through the pipeline. The entire `template` api is also exposed through `assemble`.

`gulp-assemble` is just a wrapper that takes an assemble instance and does the things that `assemble.src` and `assemble.dest` do, but without the actual reading and writing to the file system. It's recommended to use `assemble` directly if you need more functionality (like custom types and loaders).

Now, you're one the right path with your custom type and loader, but some of the documents that you pointed to are a little outdated. They all refer to using `next`, which was our first pass at loaders, but since then, we've moved to using [`loader-cache`](https://github.com/jonschlinkert/loader-cache). The only requirements are that loaders take an argument (like your glob pattern) and an `options` object. To make loaders composable, we've restricted it to one argument being passed in and one value returned. The returned value will be passed to the next loader in the chain. For `template/assemble` the last loader is required to return an object in the form of `{ key: value}` where `key` is the name of the template being stored and `value` is the actual template being stored.

With all that being said, update your loader to be like:

```js
assemble.create('product', { isRenderable: true },
  function(pattern) {
    console.log(pattern);

    var files = glob.sync(pattern);
    if (files.length === 0) {
      return null;
    }

    var templates =  _.reduce(files, function(obj, file){
      var content = fs.readFileSync(file, 'utf8');
      var name = path.basename(file, path.extname(file));

      var template = {
        name: {
          path: file,
          data: JSON.parse(content),
          content: 'dummy content to have the template pass validation'  
        }
      };

      obj[file] = template;
      return obj;
    }, {});

    // How to return > 1 template for pattern?
    return templates;
  }
);
```

> As soon as I switch to plural/globs I get the glob passed, and then I also need to handle the globbing. Why is that?

This is because the custom loader should handle the glob patterns since we won't try to make guesses about what you're passing in.

With your task setup, I recommend something like this:

```js
var assemble = require('assemble');
var push = require('assemble-push');
var extname = require('gulp-extname');

// add assemble.create for "products" code here

// define task
assemble.task('generate-html', function() {
  // Load all product metadata.
  assemble.option('layout', 'default');
  assemble.products(`source/data/**/*.json');
  return push('products')
    .pipe(extname())
    // Generate HTML from JSON metadata.
    .pipe(assemble.dest('dist'));
});

assemble.task('default', ['generate-html']);
```

Now you can run `assemble` to generate the pages.

Hope this clears some things up while we're still working on the documentation.

**Comment by agross** [comment]
@doowb, many thanks for your quick reply! In the meantime I made some progress regarding the `assemble.create()` definition myself. Your description of `gulp-assemble` and the your suggestion to use `assemble-push` instead to create the stream made it click for me. At least, I feel better now after 5 hours of work for 70 lines of code ;-)

Even though I made some progress, one question remains: Why isn't the layout applied? Do you have any pointers how I may be able to debug/log why no layout is selected (the output HTML just contains "dummy content to have the template pass validation" although my `source/layouts/product.hbs` template just pulls `data.id`)?

Here's my current gulp-integrated solution which hopefully serves others with a similar question:

```js
var _ = require('lodash');
var assemble = require('assemble');
var count = require('gulp-count');
var fs = require('fs');
var glob = require('glob');
var gulp = require('gulp');
var gutil = require('gulp-util');
var path = require('path');
var push = require('assemble-push')(assemble);
var rename = require('gulp-rename');
var tap = require('gulp-tap');

var log = require('../../log');

gulp.task('generate-html', function() {
  assemble.create('product', { isRenderable: true }, function(pattern) {
    var files = glob.sync(pattern);
    if (files.length === 0) {
      gutil.log(gutil.colors.yellow.bold('Warning:'), 'No input files for pattern', log.format(pattern));
      return {};
    }

    var templates = _.reduce(files, function(acc, file) {
      gutil.log('Reading', log.format(file));

      var json;
      try
      {
        var content = fs.readFileSync(file, 'utf8');
        json = JSON.parse(content);
      }
      catch(err)
      {
        gutil.log(gutil.colors.yellow.bold('Warning:'), 'Could not parse JSON of', log.format(file));
        return acc; // TODO: throw err;
      }

      var template = {
        path: file,
        data: json,
        content: 'dummy content to have the template pass validation'
      };

      acc[file] = template;

      return acc;
    }, {});

    return templates;
  });

  assemble.layouts('source/layouts/*.hbs');
  assemble.option('layout', 'product');
  assemble.products('source/data/2765/DE/83.json');

  return push('products')
    .pipe(rename({
      extname: '.html'
    }))
    .pipe(tap(function(file) {
      gutil.log(log.format(file));
    }))
    .pipe(assemble.dest('dist'))
    .pipe(count('Generated ## product HTML pages'));
});
```

**Comment by doowb** [comment]
This is due how we solved the problem with "sessions" in tasks. In a normal gulp pipeline, there's no way to tell `assemble.dest` the information that it needs from `assemble-push`, so we provide a "session" when you use `assemble.task`. Since  you're using `gulp.task` you don't get that session.

This should work:

```js
var _ = require('lodash');
var assemble = require('assemble');
var count = require('gulp-count');
var fs = require('fs');
var glob = require('glob');
var gulp = require('gulp');
var gutil = require('gulp-util');
var path = require('path');
var push = require('assemble-push')(assemble);
var rename = require('gulp-rename');
var tap = require('gulp-tap');

var log = require('../../log');

gulp.task('generate-html', function(done) {
  assemble.create('product', { isRenderable: true }, function(pattern) {
    var files = glob.sync(pattern);
    if (files.length === 0) {
      gutil.log(gutil.colors.yellow.bold('Warning:'), 'No input files for pattern', log.format(pattern));
      return {};
    }

    var templates = _.reduce(files, function(acc, file) {
      gutil.log('Reading', log.format(file));

      var json;
      try
      {
        var content = fs.readFileSync(file, 'utf8');
        json = JSON.parse(content);
      }
      catch(err)
      {
        gutil.log(gutil.colors.yellow.bold('Warning:'), 'Could not parse JSON of', log.format(file));
        return acc; // TODO: throw err;
      }

      var template = {
        path: file,
        data: json,
        content: 'dummy content to have the template pass validation'
      };

      acc[file] = template;

      return acc;
    }, {});

    return templates;
  });

  assemble.layouts('source/layouts/*.hbs');
  assemble.option('layout', 'product');
  assemble.products('source/data/**/*.json');

  assemble.task('default', function () {
    return push('products')
      .pipe(rename({
        extname: '.html'
      }))
      .pipe(tap(function(file) {
        gutil.log(log.format(file));
      }))
      .pipe(assemble.dest('dist'))
      .pipe(count('Generated ## product HTML pages'));
  });
  
  assemble.run(['default'], done);
});
```

Make sure to add `done` as the callback for the gulp task, and use that as the callback to `assemble.run`. You can name your internal assemble task whatever you want as long as you call it in `run`.

**Comment by jonschlinkert** [comment]
isn't this a gulpAssemble issue?

**Comment by jonschlinkert** [comment]
and no big deal just want to clarify, maybe we can move the conversation to that repo or link it there if it is, so others using gulp-assemble will see this in the history.

**Comment by jonschlinkert** [comment]
closing, so we can move this conversation to gulp-assemble if necessary. please only create issues that are assemble-specific here, all gulp-assemble issues should be on that repo.

**Comment by jonschlinkert** [comment]
also wanted to mention @agross that your example is awesome. mind if I add it to our recipes?

**Comment by agross** [comment]
@doowb Unfortunately this still doesn't work. It seems the layouts are still ignored. Some questions:

1. If I would use assemble directly (`assemblefile.js`), would I still need to `push(products)` to get them built? What would I use instead? `assemble.products(glob).pipe(assemble.dest('dist')` fails.

1. I added the following:
```js
assemble.layouts('source/layouts/*.hbs');
assemble.option('layout', 'product');
assemble.page('test-no-layout.hbs', { content: 'Test no layout', data: { id: 42 }});
assemble.page('test-layout-hash.hbs', { content: 'Test layout in hash', layout: 'product', data: { id: 42 }});
assemble.page('test-layout-2-hash.hbs', { content: 'Table layout in second hash', data: { id: 42 }}, { layout: 'product' });

return merge(push('pages'), push('products'))
  // ...
  .pipe(assemble.dest('dist'))
```

Depending on the `assemble.option('layout', 'product')` line being commented or not:
* commented: it renders without any layout
* uncommented: it renders with the `product` layout, but I cannot override if for specific pages by assigning `{ layout: 'foo' }` in the `page` "constructor".

So it seems setting the layout in a `page`'s hashes has not effect, as opposed to the [docs](https://github.com/assemble/assemble/tree/v0.6.0#layout).

Generally, I don't like that assemble does not log errors or fail when I declare  `assemble.option('layout', 'does-not-exist')`.

1. Do I need to define `assemble.engine('json', require('engine-handlebars'))` to have my JSON files laid out?

@jonschlinkert
> isn't this a gulp-assemble issue?

Probably. I have to admit, I'm a JS noob so I didn't know which library was the culprit: assemble, template, or gulp-assemble. It's still easy for me to miss the relevant parts.

> Instead of @doowb's suggestion, my recommendation is that you use assemble directly.

I'm totally OK with doing just that. It seems the result will be something very similar, all `gulp` references would just be replaced by `assemble`. Am I correct?

> wrapping assemble like that in a gulp task makes me cringe. it's definitely not idiomatic to either system.

How would I invoke assemble from gulp? I'd like the user/dev to present with a single "build" interface and since there's more non-`assemble` stuff to do to get the site built, I'd like to focus on `gulp` as the entry point.

> mind if I add it to our recipes?

:+1: Once this works I wouldn't mind at all :-)

**Comment by agross** [comment]
FYI, I found out that the `layout` property is `undefined` through `console.log(assemble.views['products']` (the same is true for `pages`):

```js
{ 'source/data/2765/DE/83.json':
   { path: 'source/data/2765/DE/83.json',
     data:
      { id: 83,
        groupId: 1584,
        // more JSON data...
        src: [Object],
        dest: [Object] },
     content: 'dummy content to have the template pass validation',
     locals: {},
     options:
      { subtype: 'products',
        isRenderable: true,
        load: 'async',
        method: 'onLoad',
        next: [Function: next],
        basePath: '',
        originalPath: 'source/data/2765/DE/83.json',
        params: {},
        route: [Object],
        engine: '.json' },
     layout: undefined,
     render: [Function],
     ext: '.json' } }
```

**Comment by agross** [comment]
After an extensive debugging session I found the following:

* As long as I don't call `assemble.option('layout', 'product')` the global layout is `null`. This causes `utils.getLayout` to be called with a global `null` layout *which then overrides any layout set on the template*. Global layouts *always* override `page` / `product`-specific layouts. Is that intended?

* As my product JSONs may contain duplicate file names in several subdirectories, I need to define a custom `renameKey` function. (Related: #619) I'd argue this is a very strange design decision. As least it doesn't make your users fall into the [Pit Of Success™](http://blog.codinghorror.com/falling-into-the-pit-of-success/). Even a simple

```js
assemble.page('one.hbs', { content: 'one' });
assemble.page('blah/one.hbs', { content: 'blah/one' });
```

will result in just one page rendered.

**Comment by doowb** [comment]
@agross For the layouts, put that on the `data` object. The `data` object is the equivalent of using front matter in a template.

```js
assemble.page('test-layout-hash.hbs', { content: 'Test layout in hash', data: { id: 42, layout: 'product' }});
```

Please open separate issues in regards to streaming loaders and `renameKey` so the topics are easier to find. Also, assemble is able to run other gulp-plugins so you could use assemble for a single "build" interface.

**Comment by jonschlinkert** [comment]
> As long as I don't call assemble.option('layout', 'product')...

I think we need to untangle how layouts are chosen. We implemented the current logic based on what we do ourselves, so any feedback on this would be great.

> As my product JSONs may contain duplicate file names in several subdirectories, I need to define a custom renameKey function. (Related: #619) I'd argue this is a very strange design decision

Well, we need to match up data with templates correctly. So if you, as a user, want to have multiple templates with the same name, and you expect assemble to magically know which template you _meant_ when you put data on the context, we have a few options: 

1. don't allow it. since object keys must be unique in javascript, and we cannot match up data correctly when two templates have the same name. This, of course, would mean that you can't do what you're doing.
2. use full file paths for all object keys and camelize the key so that in templates you would use variables like `templates_pages_marketing_splash.title`. I'm not a big fan of this option. 
3. don't decide for the user and give them a `renameKey` option so they can have multiple templates with the same name. 

We decided to go with 3, since our experience has been that only users who have advanced needs will even need to know that such an option exists. Although, I'm still a little confused on where you are with this, e.g. were you saying that you are now able to accomplish what you need with `renameKey`, or it's not working for you? 

> It seems the result will be something very similar, all gulp references would just be replaced by assemble. Am I correct?

Yes, that's correct. However, to this point:

> I'd like the user/dev to present with a single "build" interface and since there's more non-assemble stuff to do to get the site built, I'd like to focus on gulp as the entry point.

I think maybe @doowb's solution will be better for you after all (even if I don't like it :)

(and fwiw, "the pit of success" is a good thing. it's despair we don't want)

**Comment by agross** [comment]
Regarding you comment that this would make a great example, here it is: https://github.com/agross/assemble-custom-loader

Feel free to link/improve/adapt/comment.

**Comment by jonschlinkert** [comment]
awesome, thanks!
