### ISSUE TITLE
Content block

### ISSUE THREAD

**Issue by brunowego** [assemble/assemble#652]
I try add at top a block call in layout.hbs:
```hbs
{{#block 'top'}}{{/block}}
```

And in bottom another block call in layout.hbs:
````hbs
{{#block 'bottom'}}{{/block}}
```

In my pages:
```hbs
{{#content 'top'}}
<!-- build:css(.) /styles/vendor/plyr.css -->
<link rel="stylesheet" href="/bower_components/plyr/dist/css/plyr.css">
<!-- endbuild -->
{{/content}}
```

```hbs
{{#content 'bottom'}}
<!-- build:js(.) /scripts/vendor/plyr.js -->
<script src="/bower_components/plyr/dist/js/plyr.js"></script>
<script src="/bower_components/plyr/dist/js/docs.js"></script>
<!-- endbuild -->
{{/content}}
```

But not work, only call the first block. Have any idea? Thanks.

**Comment by jonschlinkert** [comment]
I'll need someone with more experience with the layouts helper to lend some wisdom here. 

(in the meantime, fyi to assemble team, since the layouts helper is going to be removed from handlebars-helpers in favor of using https://github.com/shannonmoeller/handlebars-layouts, I thought it made more sense to discuss this here)

**Comment by Sebastian-Fitzner** [comment]
To give some feedback, I need more infos. Can you post your assemble task file, the layout and your page? I use `{{blocks}}` and `{{extends}}` in almost every project so I guess it is just a setting problem ...
