### ISSUE TITLE
Render partial with YAML variable

### ISSUE THREAD

**Issue by brunowego** [assemble/assemble#664]
Have a way to render partial with YAML variable?

```hbs
---
partial: navigation
---
{{#if partial}}
  {{> partial}}
{{/if}}
```

Thanks!

**Comment by jonschlinkert** [comment]
Hey @brunowego, before I explain do you want to open the question on SO for some points, or do you want me to answer here?

**Comment by brunowego** [comment]
Thanks @jonschlinkert, you can explain here.

**Comment by jonschlinkert** [comment]
Done!

```js

**Layout**

Create a page named `layout.hbs`

```handlebars
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
  </head>
  <body>
  <!-- conditionally `button` when `foo` is true -->
  {{#if foo}}
    {{> button }}
  {{/if}}
  <body>
    {% body %}
  </body>
</html>
```

Then tell Assemble where to find it:

```js
assemble.layouts('templates/layouts/*.hbs');
```

**Page**

Create a page named `foo.hbs` or whatever you want:

```handlebars
---
layout: default
foo: true
---

This is a random page. We could put the "if" block here 
instead of the layout. Whatever makes sense for your project.
```

**Partial**

Create a partial named `button.hbs`:

```handlebars
<button>Click me!!!</button>
```

then tell Assemble where to find it:

```js
assemble.partials('templates/partials/*.hbs');
```

**Comment by brunowego** [comment]
Thanks to help me, I believe that I was not clear enough. I wish to call partial using partial a dynamic variable.

```bash
---
partial: navigation
---
{{#if partial}}
  {{> navigation}} // Here I will call the 'navigation' partial. But using YAML variable.
{{/if}}
```

**Comment by waynedpj** [comment]
do you mean having the partial name be dynamic?  Handlebars > 3.0 does this

https://github.com/wycats/handlebars.js/pull/941

hope that helps.

**Comment by jonschlinkert** [comment]
posting an example of that in a moment

**Comment by jonschlinkert** [comment]
@waynedpj that's great! no your example is closer to what he wanted and it was what I was going to suggest after his reply. I wanted to verify that we were using the latest handlebars in v0.6.0 - we should be.  

I've been wanting to find a reason to use subexpressions in partials lol. Since I haven't even used those yet, would `(partial)` be a function/helper like other subexpressions?

@brunowego actually now that I think about it, this is the easiest way probably:

```handlebars
{{#if foo}}
    {{partial bar}}
{{/if}}
```

Assemble has a built-in partial helper.  this works, just tested it. you can conditionally render any partial this way

**Comment by brunowego** [comment]
Thanks a lot @jonschlinkert, your solution works pretty good (https://www.npmjs.com/package/handlebars-helper-partial). Thanks @waynedpj :+1:

**Comment by jonschlinkert** [comment]
That helper you linked to isn't needed. Assemble has a built in partial helper

**Comment by waynedpj** [comment]
> I've been wanting to find a reason to use subexpressions in partials lol. Since I haven't even used those yet, would (partial) be a function/helper like other subexpressions?

i *thought* that they were just reusing the syntax of a subexpression and no helper is needed as `partial` can just be a variable in the context that will be evaluated as normal.  then that value for `partial` will be used to lookup the actual partial to invoke.  this is what i have seen in other template langs w/ dynamic partials, e.g. [dust.js](https://github.com/linkedin/dustjs/wiki/Dust-Tutorial#Dynamic_Partials_for_Logic).

however, i just ran some tests and it seems like you are right, the `(partial)` needs to be a [function/helper](https://github.com/wycats/handlebars.js/commit/cb51b82b8e8114aaa3e1b19c41e5c4eebf0539d5#diff-028f195e25b6b44ad89ab51f42d7dfa5R11), not just a context variable.  thanks again!

**Comment by brunowego** [comment]
@jonschlinkert, what version you say? My version is 0.4.42.

**Comment by jonschlinkert** [comment]
Ah, sorry, then the link you posted would be better
