### ISSUE TITLE
[v0.6.0] Reloading preloaded template collections

### ISSUE THREAD

**Issue by vwochnik** [assemble/assemble#683]
I can use `gulp` plugins to implement a connect server with LiveReload in my `assemblefile.js` which is working properly.

However, upon file change, I want to reload all template collections from disk before triggering the build task. The code for loading collections is executed only ONCE at the beginning of my `assemblefile.js`:

```js
assemble.data('src/data/*.{json,yml}');
assemble.partials('src/partials/*.hbs');
assemble.layouts('src/layouts/*.hbs');
assemble.indices('src/indices/*.hbs');
```

**Comment by jonschlinkert** [comment]
Unless someone comes up with a more idiomatic solution, you'll need to define those inside the task that's being reloaded.

**Comment by vwochnik** [comment]
Ok, that is a good-enough solution, I think.

Please spare your time once more: I've ran into the problem that my `index` plugin messes up the `{{assets}}` helper path so I've looked for a better way of rendering index templates. Of course, this reduces the flexibility of the plugin since `postprocess`ing is gone but that is irrelevant for this use case anyways.

Here it is:
https://github.com/vwochnik/assemble-plugin-index/blob/master/lib/index.js

**Comment by jonschlinkert** [comment]
> I've ran into the problem that my index plugin messes up the {{assets}}

hmm, can you give more details about that? what is the issue you're running into specifically? happy to help

**Comment by vwochnik** [comment]
It didn't calculate the paths since I manually `.render()`ed the templates. Now they're being pushed through the pipe instead. But could you please look at it so I know I'm doing things right? Right now, I'm doing this work since I need a plugin like that but I'd like people to use my plugin when `assemble` is finally ready.

**Comment by jonschlinkert** [comment]
I'll pull it down tomorrow and take a look, at first glance it looks great!

**Comment by vwochnik** [comment]
Ok, I improved it a lot again. ;) Uni's getting boring lately.

**Comment by doowb** [comment]
@vwochnik `{{assets}}` is a computed property added to the template's `data` property in an `onLoad` middleware. Since [right here](https://github.com/vwochnik/assemble-plugin-index/blob/master/lib/index.js#L98-L99) you're adding the template to the `assemble.views.pages` collection directly, you're by-passing the `onLoad` middleware. Also, due to the way assemble handles sessions inside tasks, you might be adding the template to the wrong collection.

I'm going to take a closer look and provide an example (or PR) that's more idiomatic to assemble. I think the rest of the code looks good. Thanks for putting this together!

**Comment by jonschlinkert** [comment]
closing since this seems to have been resolved.
