### ISSUE TITLE
YAML within markdown as includes/partials

### ISSUE THREAD

**Issue by briantjacobs** [assemble/assemble#685]
Hi, assemble has been great so far! But I've run into some confusing behavior when it comes to using markdown as partials...

I have this as an option in my assemble config

```handlebars
partials: '<%= yeoman.app %>/{_content,_includes}/*.{hbs,html,md}',
```

If I use this in a page thats being used in a layout...

```handlebars
{{md "app/_content/test.md" }}
```
The html gets rendered, but if there's YAML frontmatter in there, it's parsed as markdown

If I use this...

```handlebars
{{md test }}
```
Nothing gets rendered at all

If I use this...

```handlebars
{{> test }} 
```
The raw markdown gets rendered

And then if I use this...

```handlebars
{{#markdown}}
  {{> test }}
{{/markdown}}
```
The markdown gets rendered as HTML, and any YAML frontmatter within can be used as variables.

So, a few issues here:
1. I can't use YAML frontmatter if I'm using the md handlebars helper. Is this expected behavior? Is it wrong to want to use frontmatter within a markdown partial?
2. It's a little confusing that if I want to use markdown as a partial I have to use a different syntax.

**Comment by jonschlinkert** [comment]
> assemble has been great so far! 

Thanks! 

The behavior your describing is all expected. Keep in mind that the markdown helper is "dumb" from the standpoint that it just wants to parse markdown. If we want to also parse front-matter, it's probably better to use a different helper alongside the markdown helper. (see below)

Here's what's happening in your setup, so you can see how some of this works (fwiw this is mostly handlebars conventions, not really assemble per se).

The following is just reading the file path and returning a string since the path doesn't match up directly with the basename of any of the partials that were loaded in the assemble config. 

```handlebars
{{md "app/_content/test.md" }}
```

since it's just a string and not a registered partial or template, assemble doesn't do anything special to it and the markdown parser thinks that `---` is either a horizontal rule (I prefer using `***` for this reason), or a Setext-style markdown header, like:

```markdown
Foo
---
```

**Solutions**

> 1. I can't use YAML frontmatter if I'm using the md handlebars helper. 

You can, but the `md` helper won't do anything with front matter. You need to parse the front matter before the string gets to the markdown helper. This is exactly why markdown is parsed by helpers and not by an engine. Sometimes you need fine-grained control over exactly where markdown is parsed.

To show you how to parse the front matter with a helper, I created [this helper](https://github.com/helpers/helper-front-matter) as an example. It most likely will need to be customized for your use case. If so and I have time before I leave for vacation this weekend I'll put something together for you.

> Is this expected behavior? Is it wrong to want to use frontmatter within a markdown partial?

Yes, and no. :)

> 2. It's a little confusing that if I want to use markdown as a partial I have to use a different syntax.

Your using handlebars, so we have to work within the constructs of the syntax. IMHO it makes total sense to use `{{md "foo/bar"}}` for including external content a block helper for wrapping inline content. But this is probably a taste thing.

Fwiw, if you have the ability to use Assemble v0.6.0, none of these challenges are present.

**Comment by briantjacobs** [comment]
I appreciate the detailed reply and for posting the helper example. This all makes sense. I guess it's all kind of a moot point if it's a non-issue in 0.6.0.

**Comment by jonschlinkert** [comment]
you're welcome!

**Comment by jonschlinkert** [comment]
closing based on age and since this seems to have been resolved
