### ISSUE TITLE
v0.6 Front matter to plugin

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#690]
I tried to google, but none of the posts were useful.

I've loaded the files, and then piped them into a very simple plugin. In that, I would like to get ahold of the front matter of each file. How do I do that?

(and on a not-related, but possibly useful note: Would you object to me adding the label 'v0.6' and tag the relevant issues, to easier find what has and hasn't been brought up re: next version?)

**Comment by vwochnik** [comment]
It's actually very simple but not yet documented. It's not relevant whether you are dealing with `vinyl` files or `template`s at this time (and my knowledge).

So, let's suppose you are in the plugin function:

```js
function(file, enc, cb) {
    console.log("Title: " + file.data.title);
    this.push(file); // -- or cb(null, file);
}
```

Front matter is fount in the `data` property of each file.

**Comment by Melindrea** [comment]
Thank you, exactly what I needed.

**Comment by jonschlinkert** [comment]
thanks @vwochnik! keep in mind that the format above is for plugins only. 

you can accomplish the same in middleware like this:

```js
assemble.preRender(/\.md/, function(file, next) {
  console.log(file.data);
  next()
});
```

**Comment by vwochnik** [comment]
If you don't mind: Would it be possible to access the session's context in the `preRender` middleware so that it is possible to only insert data specific to the ONE task that the middleware has been called in?

Let's say I have a `preRender` function that inserts data into the `session` that is then used by the `template`. Possible?
