### ISSUE TITLE
v0.6.0 Exceptions handeling 

### ISSUE THREAD

**Issue by Zackio** [assemble/assemble#704]
If I get a helper wrong, like it doesn't exist or I close it incorrectly, it creates a exception.

<pre>
      throw exception;
            ^
Error: lt doesn't match embed - 4:4
    at new Error (<anonymous>)

etc...
</pre>

This means it breaks the watch and I have to start it again from the terminal. Is there a way I can stop this from breaking the watch?

**Comment by jonschlinkert** [comment]
sorry for the late reply. I think this should be fixed in the latest assemble (on the dev branch). we also added a feature called "rethrow", which optionally prints out to the terminal the specific location that a syntax error happened, with a line number and the template in which the error occurred. If you still have this issue, please repoen.
