### ISSUE TITLE
Tiered data folder to match site structure

### ISSUE THREAD

**Issue by depiction** [assemble/assemble#754]
Is is possible to have the data folder match the pages folder structure? I'm working on a multi-lingual site with each language in a sub-folder and each version having multiple levels of pages.

Currently the data folder is very flat and pages have an extension on the end indicating the language (page-en.json and page-de.json). I also can't name the index page for each folder index.html because that would result in duplicate index.json files.

It would be nice if the data and page folder structures matched. Are there any workarounds with grunt or can this be added in future versions?

**Comment by jonschlinkert** [comment]
this is totally doable in assemble of any version. the latest assemble (0.6.0) makes this easy. since this question was about the grunt-assemble plugin, I'm closing here, but you can reopen on that repo if you still have the question about the grunt plugin.  might be worthing taking a look at [assemble-pattern-lab](https://github.com/assemble/assemble-pattern-lab) to see how custom paths can be used/generated

**Comment by depiction** [comment]
Can you provide an example? Neither the assemble documentation or the assemble-pattern-lab mention anything about tiered data folders.

**Comment by jonschlinkert** [comment]
is the project you're working on public? I'd be happy to take a look and give feedback on a specific goal. otherwise this is probably a better question for stackoverflow IMHO
