### ISSUE TITLE
Cannot complete Quickstart: Gruntfile missing

### ISSUE THREAD

**Issue by DawnPaladin** [assemble/assemble#759]
I feel like I must be missing something really obvious. I can't even get through the Quickstart. I ran these commands:

    git clone https://github.com/assemble/assemble.git "my-project"
    cd my-project
    npm install

All of these completed without error. But when I run `grunt assemble`, I get "Fatal error: Unable to find local grunt. If you're seeing this message, either a Gruntfile wasn't found or grunt hasn't been installed locally to your project."

I looked in the assemble.git repository (v0.6.0 branch) and I don't see a gruntfile there. What am I missing?

**Comment by doowb** [comment]
We're finishing up a refactor of assemble and switched the default branch on github to 0.6.0. The Quickstart still refers to the master branch. You can switch to the master branch by doing:

```sh
$ git checkout master
```

Then do `npm install` and `grunt assemble`.

Additionally, the `0.4.x` version of assemble has been moved to `grunt-assemble` since that code is the actual grunt plugin. You can follow the same quickstart instructions by cloning `https://github.com/assemble/grunt-assemble.git "my-project"` instead.

Sorry for the confusion. We're working on cleaning everything up.

**Comment by DawnPaladin** [comment]
That helps, thank you! Switching to master branch allowed me to `grunt assemble` and `grunt build` successfully. That completed, I'm not seeing the `src` directory that the Quickstart says should be there. What's my next step?

**Comment by doowb** [comment]
>  you should start with a nice clean Gruntfile and a brand new src directory

What's in master uses templates from the `test/fixtures` directory. You can look at the Gruntfile and those fixtures, but it's better to look at the examples link in the quick start for a simpler getting started.

If this is the only thing that you're using Grunt for, then I would recommend taking a look at [template](https://github.com/jonschlinkert/template) and the [examples](https://github.com/jonschlinkert/template/tree/master/examples) there. The assemble refactor (0.6.0) is uses template and can be used standalone.
