### ISSUE TITLE
Future of assemble

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#763]
Hi,

sorry for this question, but I am following this project nearly every day and I am a bit afraid that the last commit on 0.6.0-dev was back in May 2015 ...
Can you give us a rough roadmap when and what is planned?

Regards
Stefan

**Comment by jonschlinkert** [comment]
> I am a bit afraid that the last commit on 0.6.0-dev was back in May 2015 ...

Check branches! lol https://github.com/assemble/assemble/tree/dev (jk, this is something we need to do better at. we're working on a plan for communication)

We've been working hard on all of the libraries that support the assemble ecosystem. Assemble is very, very important to us. We have some amazing (and huge) features on the way, but I'd rather not mention too much yet. Nothing is hidden or private. As a hint, if you watch the projects every day you might see a pattern emerging in the projects we're working on ;) Soon I'll publish a detailed overview and "guide" to how all of this fits together - that's an actual goal of ours. 

thanks for caring!

**Comment by jonschlinkert** [comment]
closing since not an issue

**Comment by stefanwalther** [comment]
@jonschlinkert, OK, thx, just seen dev ;-)

**Comment by rcherny** [comment]
I've been watching this with baited interest as well, though I confess only with one eye. I've seen all the related projects you guys are working on — it's all incredible. That said, Assemble continues to be one of my favorite "let's churn out a static site with lots of parts" frameworks. That said, I can't help but wonder if 0.4.x is a dead-end or if 0.6.x *alpha/beta* whatever is even production stable at this point — not to mention the lack of coherent docs makes me afraid to even try to use it.

Am I missing something obvious? Is #551 the latest information, basically?

**Comment by jonschlinkert** [comment]
> not to mention the lack of coherent docs makes me afraid to even try to use it.

I can't blame you there lol. new docs will be launched very soon. that's really the main thing missing from the next release. however... it might help if I put this in a broader perspective. 

We've been "ready" to launch the next version of assemble for a while now, but the reason we haven't is that we're working on a few other pieces of the puzzle that will be key to assemble's future. Initially, @doowb and I thought it would be possible to launch these other things one by one, which would have been great because we could just get assemble released and then add these other things. 

In reality though, as we started working on these other projects, it started opening up our eyes to how everything really fits together, and some of these things meant we would need to make architectural changes to assemble. The API, however, might not change much at all from what's there in 0.6.0 currently. Sorry to be so vague, it has more to do with setting expectations than trying to keep things "private". Like I mentioned earlier, all of the parts of this "puzzle" I mention are completely open source and publicly visible, but I'm not quite ready to describe my overall plan for them. 

That said... we might be formally introducing a very important part of this puzzle in the next day or so . after that, you might be able to draw better inferences about the rest :)

**Comment by rcherny** [comment]
Hey @jonschlinkert thanks so much for all the incredible hard work and the response. I appreciate it. What I am wondering now is really — if I was to roll a new site / set up using Assemble should I be using 0.6.x and if so, how stable might it be going forwards? 

Your comment about the API not changing much going forwards is encouraging. When / if you do introduce changes *do you have plans* to be supportive of backwards compatibility for 0.6.x to some degree, at least with changes noted, patching instructions, etc.? I guess I'm just wondering how stable it's likely to be, bottom line. Hope that makes sense.

If these things just haven't been decided, I understand and that's fine too. But even knowing "a plan is TBD" is something for my decision process.

If waiting is better, that's not a huge issue, just trying to plan ahead and make responsible decisions. We just re-launched a [project of ours](http://isobar-idev.github.io/code-standards/) using the ancient Assemble 0.4.x codebase for the build tool, but it feels ... dated, or something :)

Thanks again!

**Comment by jonschlinkert** [comment]
> I guess I'm just wondering how stable it's likely to be, bottom line

totally understand, I forgot to answer the actual point lol. We're feeling really good about usability atm, the API itself will not change much after 0.6 is released. However, until 0.6.0 is actually released, there might be some tweaks - I honestly can't think of anything offhand, but it could happen. Does this answer what you're asking about stability?

As for docs/changelog, we will definitely be documenting changes in assemble going forward. especially if an API changes were to happen. This will be easier for us to do (time-wise) once we at least get assemble off of the old docs.

fwiw we also plan to continue to support (and update) the grunt plugin.

(thanks for the kind words!)
