### ISSUE TITLE
Running Assemble in vanilla Nodejs?

### ISSUE THREAD

**Issue by shukriadams** [assemble/assemble#773]
I'd like to run Assemlble in a project that's built in plain NodeJS (ie, without Grunt) but there's no NPM release of Assemble that supports this. I noticed
https://github.com/assemble/assemble/issues/498 mentions a v0.5 rewrite of Assemble which should do just this, but as far as I can tell neither 0.5 or 0.6 are officially released yet. Any word on when we'll get Assemble in NodeJs? Is anyone else doing this already? Is the 0.5 or 0.6 branch stable enough to bake directly into my project?

**Comment by jonschlinkert** [comment]
you can always do `npm i assemble/assemble#dev` to get the latest release. 

> as I can tell neither 0.5 or 0.6 are officially released yet.

no, but there have been something like 850 commits since issue 458. see [the dev branch](https://github.com/assemble/assemble/tree/dev)

> stable enough to bake directly into my project?

The API shouldn't change from where it is on the dev branch. but we won't be providing support for anything in dev since it takes us away from making progress on merging it into master and getting docs written. so unless you're willing to figure things out on your own, I'd stick with grunt-assemble until we release 0.6

**Comment by shukriadams** [comment]
Thanks for the fast reply Jon - that made it a lot easier for me to commit to a direction with my own project. Looking forward to 0.6!

**Comment by jonschlinkert** [comment]
great! 

if you want to try using 0.6, as fate would have it, I went ahead and published [assemble-core](https://github.com/assemble/assemble-core) today. assemble-core has a complete API and all of the core functionality of assemble 0.6.0 - but it does not have any built-in collections (like `pages`, `partials`, etc) or default settings for template engines. 

**view collections**

Here is how you would add a collection:

```js
var assemble = require('assemble-core');
var app = assemble();

app.create('pages');
```

Done. Now you can load pages with `app.pages('*.hbs')`

**engine**

To add an engine:

```js
app.engine('hbs', require('engine-handlebars');
```

Now assemble will render handlebars templates using `engine-handlebars`. 

**rendering templates**

Example of rendering templates using `src` (gulp-style):

```js
app.src('*.hbs')
  .pipe(app.renderFile())
  .pipe(dest('foo'));
```

Example of rendering templates from a collection:

```js
app.pages('*.hbs');
app.toStream('pages')
  .pipe(app.renderFile())
  .pipe(dest('foo'));
```
