### ISSUE TITLE
What version is 'current' What is up with 0.4 vs 0.6 vs 0.5?

### ISSUE THREAD

**Issue by thedamon** [assemble/assemble#774]
Really confused what's going on with development.

Whenever I'm reading a doc, I don't know what version it's talking about...
We have 0.4.X because that's what is on npm, but the default branch on here and that everyone seems to be talking about is 0.6.X.

Will 0.6.X have a release roadmap?

Just not sure what's goin on..

**Comment by jonschlinkert** [comment]
> Really confused what's going on with development.

`dev` is the latest dev branch. [here is everything you need to know](https://github.com/assemble/assemble/pull/767) about 0.6. As you can see from the commit history, we're super busy actually writing code trying to release 0.6. If you're unsure about what's happening, I'm sorry about the lack of docs, I know it's frustrating and we're not happy about it either. But we think it's best for us to stay focused on making this release as awesome as possible.

For now, since you seem unsure about 0.6 I recommend that you stick with grunt-assemble until we have documentation up

**Comment by thedamon** [comment]
Any estimate on 0.6 being stable? I fully understand you may not be able to answer, but we are thinking to be looking to get off grunt at the next station

**Comment by jonschlinkert** [comment]
We just published assemble-core, which is stable. It's assemble 0.6.0 without the presets
