### ISSUE TITLE
Cannot set property base of Base

### ISSUE THREAD

**Issue by grayghostvisuals** [assemble/assemble#926]
## Prerequisites

- [x] Have you searched for existing issues (open and close) to see if the bug or feature request has already been reported?
- [x] If this is a bug report, are you running the latest version of Assemble? If not, please update to the latest version and verify that the issue still occurs before proceding.
- [x] Have you read the [Contributing Guide](contributing.md)?
- [x] Have you reviewed the project readme (you might find advice about creating new issues)?
- [x] Are you creating an issue in the correct repository? (For example, if your issue is related to [grunt-assemble][] or [handlebars-helpers][], you will want to create the issue in that project).

Ready? Great! Please provide the following details:

## version 

0.24.3

## description

Upgraded to 0.24.3 from 0.9.1 and encountered compiling errors

## error message

```sh
TypeError: Cannot set property base of #<Base> which has only a getter
```

## assemblefile.js

Here's the link to the gulpfile showing the lines for my assemble task that @doowb also helped with.
[https://github.com/grayghostvisuals/site/blob/development/gulpfile.js#L168-L344](https://github.com/grayghostvisuals/site/blob/development/gulpfile.js#L168-L344)

**Comment by doowb** [comment]
@grayghostvisuals I'm taking a look at this. Thanks for the issue.

**Comment by doowb** [comment]
@grayghostvisuals I pulled down your repo and updated to `assemble@0.24.3` (on the `development` branch). I'm not getting an error.

System stats:
 - OS X 10.12.1
 - node 6.10.1
 - npm 5.0.1

What I did:

```
$ git checkout development
$ git pull origin development
$ rm -fr node_modules # this is to ensure other something isn't wrong in node_modules
$ npm i assemble@latest --save
$ npm i
$ gulp
```

To ensure that NPM pulled down the correct dependencies I removed `node_modules`, installed `assemble`, then installed the rest. You could also update the assemble version in `package.json` and just run `npm i`.

Since it worked, I also removed `node_modules` again, then did `npm cache clear --force && npm i`.

Let us know what node and npm versions you're using and we'll try with those.

**Comment by grayghostvisuals** [comment]
@doowb Doh! I should have checked my version of Node first. I was running Node 4. I switched to Node 6.10.2 and now running Assemble's latest. Thanks for checking. Appreciate it very much. 🏖
